@echo off

REM --- Archivos C ---
set FILES=src\glad.c src\main.c

REM --- Librerías ---
set LIBS="E:\NACHO\ESTUDIO\PROYECTOS\PROGRAMACION\GAME ENGINE\GAMEENGINE_GAME\lib\SDL2main.lib" ^
         "E:\NACHO\ESTUDIO\PROYECTOS\PROGRAMACION\GAME ENGINE\GAMEENGINE_GAME\lib\SDL2.lib" ^
         "E:\NACHO\ESTUDIO\PROYECTOS\PROGRAMACION\GAME ENGINE\GAMEENGINE_GAME\lib\freetype.lib"

REM --- Compilación ---
CL /Zi /I "E:\NACHO\ESTUDIO\PROYECTOS\PROGRAMACION\GAME ENGINE\GAMEENGINE_GAME\include" %FILES% /link %LIBS% /OUT:mygame.exe
